---
  - name: 'extract zipped backend'
    become: yes
    copy:
      src: ~/project/backend.tar.gz
      dest: /home/ubuntu/backend.tar.gz


  - name: "delete anything that might already be running"
    become: true
    command: pm2 delete all
    ignore_errors: true

  - name: "start server"
    become: true
  # command: pm2 start -f ./main.js
    shell: |
        cd /home/ubuntu
      # mkdir app
      # mv backend.tar.gz app/backend.tar.gz
      # cd app
        tar xzvf backend.tar.gz 
        npm i 
        npm run build
        pm2 stop default
        pm2 start npm -- start

    args:
      chdir: /home/ubuntu/app/backend
    environment:
     ENVIRONMENT: production
     TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
     TYPEORM_MIGRATIONS_DIR: "./migrations"
     TYPEORM_MIGRATIONS: "./migrations/*.ts"
     TYPEORM_ENTITIES: "./modules/domain/**/*.entity.ts"
     TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
     TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
     TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
     TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
     TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"




     